<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Authors>Cemalettin Dervis, Michael Tsai, Justxn</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/ptraced/SharpConfig.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Copyright>Copyright Cemalettin Dervis, Michael Tsai, Justxn</Copyright>
    <Description>An easy to use CFG/INI configuration library for .NET.</Description>
    <PackageIcon>SharpConfigLogo.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/ptraced/SharpConfig</PackageProjectUrl>
    <PackageId>$(AssemblyName)-Reworked</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\SharpConfigLogo.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="SharpConfigLogo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
